//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.27 at 05:22:33 PM GMT 
//


package generatedSelec;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Song_QNAME = new QName("", "song");
    private final static QName _Creator_QNAME = new QName("", "creator");
    private final static QName _Director_QNAME = new QName("", "director");
    private final static QName _AirDate_QNAME = new QName("", "airDate");
    private final static QName _Link_QNAME = new QName("", "link");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _NEps_QNAME = new QName("", "nEps");
    private final static QName _DateEnd_QNAME = new QName("", "dateEnd");
    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _CharName_QNAME = new QName("", "charName");
    private final static QName _Platform_QNAME = new QName("", "platform");
    private final static QName _NSeasons_QNAME = new QName("", "nSeasons");
    private final static QName _Network_QNAME = new QName("", "network");
    private final static QName _Number_QNAME = new QName("", "number");
    private final static QName _DateStart_QNAME = new QName("", "dateStart");
    private final static QName _Price_QNAME = new QName("", "price");
    private final static QName _Genre_QNAME = new QName("", "genre");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _LastEp_QNAME = new QName("", "lastEp");
    private final static QName _Season_QNAME = new QName("", "season");
    private final static QName _Writer_QNAME = new QName("", "writer");
    private final static QName _SocialNetwork_QNAME = new QName("", "socialNetwork");
    private final static QName _Value_QNAME = new QName("", "value");
    private final static QName _FirstEp_QNAME = new QName("", "firstEp");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Scatalog }
     * 
     */
    public Scatalog createScatalog() {
        return new Scatalog();
    }

    /**
     * Create an instance of {@link Serie }
     * 
     */
    public Serie createSerie() {
        return new Serie();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link Episode }
     * 
     */
    public Episode createEpisode() {
        return new Episode();
    }

    /**
     * Create an instance of {@link AvailableOn }
     * 
     */
    public AvailableOn createAvailableOn() {
        return new AvailableOn();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link Actor }
     * 
     */
    public Actor createActor() {
        return new Actor();
    }

    /**
     * Create an instance of {@link Search }
     * 
     */
    public Search createSearch() {
        return new Search();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "song")
    public JAXBElement<String> createSong(String value) {
        return new JAXBElement<String>(_Song_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "creator")
    public JAXBElement<String> createCreator(String value) {
        return new JAXBElement<String>(_Creator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "director")
    public JAXBElement<String> createDirector(String value) {
        return new JAXBElement<String>(_Director_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "airDate")
    public JAXBElement<XMLGregorianCalendar> createAirDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AirDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "link")
    public JAXBElement<String> createLink(String value) {
        return new JAXBElement<String>(_Link_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nEps")
    public JAXBElement<BigInteger> createNEps(BigInteger value) {
        return new JAXBElement<BigInteger>(_NEps_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dateEnd")
    public JAXBElement<XMLGregorianCalendar> createDateEnd(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateEnd_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "charName")
    public JAXBElement<String> createCharName(String value) {
        return new JAXBElement<String>(_CharName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "platform")
    public JAXBElement<String> createPlatform(String value) {
        return new JAXBElement<String>(_Platform_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nSeasons")
    public JAXBElement<BigInteger> createNSeasons(BigInteger value) {
        return new JAXBElement<BigInteger>(_NSeasons_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "network")
    public JAXBElement<String> createNetwork(String value) {
        return new JAXBElement<String>(_Network_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number")
    public JAXBElement<BigInteger> createNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_Number_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dateStart")
    public JAXBElement<BigInteger> createDateStart(BigInteger value) {
        return new JAXBElement<BigInteger>(_DateStart_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "price")
    public JAXBElement<BigDecimal> createPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Price_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "genre")
    public JAXBElement<String> createGenre(String value) {
        return new JAXBElement<String>(_Genre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastEp")
    public JAXBElement<XMLGregorianCalendar> createLastEp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_LastEp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "season")
    public JAXBElement<BigInteger> createSeason(BigInteger value) {
        return new JAXBElement<BigInteger>(_Season_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "writer")
    public JAXBElement<String> createWriter(String value) {
        return new JAXBElement<String>(_Writer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "socialNetwork")
    public JAXBElement<String> createSocialNetwork(String value) {
        return new JAXBElement<String>(_SocialNetwork_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value")
    public JAXBElement<BigDecimal> createValue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Value_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "firstEp")
    public JAXBElement<XMLGregorianCalendar> createFirstEp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_FirstEp_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
